# Generated by Django 6.0.3 on 2026-08-25 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('membership_type', models.CharField(choices=[('STD', 'Standard'), ('VIP', 'VIP')], default='STD', max_length=10)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('weight', models.FloatField(help_text='Cân nặng (kg)')),
                ('height', models.FloatField(help_text='Chiều cao (cm)')),
                ('body_fat', models.FloatField(blank=True, help_text='Tỷ lệ mỡ (%)', null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlygym.member')),
            ],
        ),
    ]
