# Generated by Django 6.0.3 on 2026-08-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlygym', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề bài viết')),
                ('summary', models.CharField(max_length=300, verbose_name='Tóm tắt ngắn')),
                ('content', models.TextField(verbose_name='Nội dung chi tiết')),
                ('image_url', models.URLField(max_length=500, verbose_name='Đường dẫn ảnh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên khu vực / Thiết bị')),
                ('category', models.CharField(choices=[('CARDIO', 'Khu Cardio'), ('WEIGHTS', 'Khu Tập Tạ'), ('STUDIO', 'Phòng Yoga & GroupX'), ('RELAX', 'Tiện Ích & Xông Hơi')], default='CARDIO', max_length=20, verbose_name='Phân loại')),
                ('description', models.TextField(verbose_name='Mô tả chi tiết')),
                ('image_url', models.URLField(max_length=500, verbose_name='Đường dẫn ảnh')),
            ],
        ),
    ]
