# Generated by Django 6.0.3 on 2026-08-28 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlygym', '0002_article_facility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('phone', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('service', models.CharField(choices=[('TRIAL', 'Đăng ký tập thử miễn phí'), ('PT', 'Thuê HLV cá nhân (PT 1:1)'), ('YOGA', 'Đăng ký lớp Yoga / Dance')], default='TRIAL', max_length=20, verbose_name='Dịch vụ quan tâm')),
                ('booking_date', models.DateField(verbose_name='Ngày hẹn tập')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú thêm')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ liên hệ'), ('CONFIRMED', 'Đã xác nhận'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên người gửi')),
                ('rating', models.IntegerField(choices=[(1, '1 Sao ⭐'), (2, '2 Sao ⭐'), (3, '3 Sao ⭐'), (4, '4 Sao ⭐'), (5, '5 Sao ⭐')], default=5, verbose_name='Đánh giá')),
                ('comment', models.TextField(verbose_name='Ý kiến góp ý')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Duyệt hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
