# Generated by Django 6.0.3 on 2026-08-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlygym', '0003_booking_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên HLV')),
                ('specialty', models.CharField(max_length=100, verbose_name='Chuyên môn (VD: Giảm cân, Yoga)')),
                ('experience', models.IntegerField(verbose_name='Năm kinh nghiệm')),
                ('bio', models.TextField(verbose_name='Giới thiệu bản thân')),
                ('image_url', models.URLField(max_length=500, verbose_name='Đường dẫn ảnh chân dung')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='expire_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày hết hạn'),
        ),
    ]
