# Generated by Django 6.0.3 on 2026-08-30 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlygym', '0004_trainer_member_expire_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên chi nhánh')),
                ('address', models.CharField(max_length=255, verbose_name='Địa chỉ')),
                ('phone', models.CharField(max_length=15, verbose_name='Hotline')),
                ('opening_hours', models.CharField(default='05:30 - 22:00', max_length=100, verbose_name='Giờ mở cửa')),
                ('image_url', models.URLField(max_length=500, verbose_name='Ảnh chi nhánh')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Câu hỏi')),
                ('answer', models.TextField(verbose_name='Câu trả lời')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
            ],
        ),
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên gói tập')),
                ('price', models.IntegerField(verbose_name='Giá tiền (VNĐ)')),
                ('duration_days', models.IntegerField(default=30, verbose_name='Thời hạn (Số ngày)')),
                ('description', models.TextField(verbose_name='Mô tả quyền lợi')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Gói nổi bật')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.URLField(max_length=500, verbose_name='Ảnh bìa'),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.CharField(max_length=300, verbose_name='Tóm tắt'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(verbose_name='Ngày hẹn'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Họ tên'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.CharField(choices=[('TRIAL', 'Tập thử miễn phí'), ('PT', 'Thuê HLV Cá Nhân (1:1)'), ('YOGA', 'Lớp GroupX / Yoga')], default='TRIAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ liên hệ'), ('CONFIRMED', 'Đã xác nhận'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='facility',
            name='category',
            field=models.CharField(choices=[('CARDIO', 'Khu Cardio'), ('WEIGHTS', 'Khu Tập Tạ'), ('STUDIO', 'Phòng Yoga & GroupX'), ('RELAX', 'Tiện Ích & Xông Hơi')], default='CARDIO', max_length=20),
        ),
        migrations.AlterField(
            model_name='facility',
            name='description',
            field=models.TextField(verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên thiết bị'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 Sao ⭐'), (2, '2 Sao ⭐'), (3, '3 Sao ⭐'), (4, '4 Sao ⭐'), (5, '5 Sao ⭐')], default=5),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='image_url',
            field=models.URLField(max_length=500, verbose_name='Đường dẫn ảnh'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='specialty',
            field=models.CharField(max_length=100, verbose_name='Chuyên môn'),
        ),
        migrations.AddField(
            model_name='member',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanlygym.branch', verbose_name='Chi nhánh đăng ký'),
        ),
        migrations.CreateModel(
            name='CheckInLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_time', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlygym.branch')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlygym.member')),
            ],
        ),
        migrations.CreateModel(
            name='GymClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tên lớp học')),
                ('day_of_week', models.CharField(choices=[('MON', 'Thứ Hai'), ('TUE', 'Thứ Ba'), ('WED', 'Thứ Tư'), ('THU', 'Thứ Năm'), ('FRI', 'Thứ Sáu'), ('SAT', 'Thứ Bảy'), ('SUN', 'Chủ Nhật')], max_length=3, verbose_name='Ngày học')),
                ('start_time', models.TimeField(verbose_name='Giờ bắt đầu')),
                ('end_time', models.TimeField(verbose_name='Giờ kết thúc')),
                ('max_capacity', models.IntegerField(default=20, verbose_name='Số lượng học viên tối đa')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlygym.branch', verbose_name='Chi nhánh')),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanlygym.trainer', verbose_name='HLV Phụ trách')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Số tiền thanh toán')),
                ('payment_method', models.CharField(choices=[('TRANSFER', 'Chuyển khoản QR'), ('CASH', 'Tiền mặt tại quầy')], default='TRANSFER', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Chờ thanh toán'), ('PAID', 'Đã thanh toán'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlygym.member')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlygym.membershipplan')),
            ],
        ),
        migrations.CreateModel(
            name='ClassEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlygym.member')),
                ('gym_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlygym.gymclass')),
            ],
            options={
                'unique_together': {('member', 'gym_class')},
            },
        ),
    ]
